// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytbfLLTbpBbab_wJGWQvZH1zfeRMT0ac',
    appId: '1:383477928440:android:213c91a43578c4b282460d',
    messagingSenderId: '383477928440',
    projectId: 'rlye-478cc',
    storageBucket: 'rlye-478cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJgyBm1T8VZxcoS22d0njtdD4et7R9Bo',
    appId: '1:383477928440:ios:df8e8c139d4eb0d182460d',
    messagingSenderId: '383477928440',
    projectId: 'rlye-478cc',
    storageBucket: 'rlye-478cc.appspot.com',
    androidClientId:
        '383477928440-vp2vkc0570b1t7pdmpt20ikuc8qrc0nf.apps.googleusercontent.com',
    iosClientId:
        '383477928440-21lb6mi0hn9hlvk6i7u6405c0ff4ce97.apps.googleusercontent.com',
    iosBundleId: 'com.ryle.client',
  );
}